[package]
name = "writer2"
version = "0.1.0"
authors = ["name <e@ma.il>"]

[dependencies]
getopts = "0.2"
libc = "0.2"
bitflags = "1.0"
newtype_derive = "0.1.6"
custom_derive = "0.1.7"

[build-dependencies]
cc = "1.0"
bindgen = "0.26.3"
