
#ifndef CMARK_EXPORT_H
#define CMARK_EXPORT_H

#ifndef CMARK_EXPORT
#define CMARK_EXPORT
#endif

#ifndef CMARK_NO_EXPORT
#define CMARK_NO_EXPORT
#endif

#ifndef CMARK_DEPRECATED
#  define CMARK_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef CMARK_DEPRECATED_EXPORT
#  define CMARK_DEPRECATED_EXPORT CMARK_EXPORT CMARK_DEPRECATED
#endif

#ifndef CMARK_DEPRECATED_NO_EXPORT
#  define CMARK_DEPRECATED_NO_EXPORT CMARK_NO_EXPORT CMARK_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define CMARK_NO_DEPRECATED
#endif

#endif
